### ISSUE TITLE
Run on Juno?

### ISSUE THREAD

**Issue by hezral** [stsdc/goldensection#1]
Hi, i happened to found this based on searching for Granite and Python code on Github. 
I'm also trying to use Granite in Python on Juno but it doesn't seem to work. Have you had success on running your code successfully? Btw, i'm also using the same template that you've based on.

**Comment by stsdc** [comment]
I was developing this project on Loki. Didn't test it on Juno. Sorry.

**Comment by hezral** [comment]
Thanks. Worth a shot to ask :)
